services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "4173:4173"
    networks:
      - app

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: twitter
      MONGO_INITDB_ROOT_USERNAME: m0ng0db
      MONGO_INITDB_ROOT_PASSWORD: p4ssw0rd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

  minio:
    image: 'minio/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - "9000:9000"
      - "8900:8900"
    volumes:
      - 'minio:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'
    networks:
      - app

networks:
  app:
    driver: bridge