services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-dev
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    networks:
      - app

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend-dev
    env_file:
      - frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - app

  minio:
    image: 'minio/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - "9000:9000"
      - "8900:8900"
    volumes:
      - 'minio:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'

networks:
  app:
    driver: bridge

volumes:
  minio:
    driver: local