FROM python:3.9-slim

RUN apt update -y && \
    apt install -y ffmpeg libsm6 libxext6

RUN python -m pip install --no-cache-dir --upgrade pip

WORKDIR /app

COPY . .

RUN python -m pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "api.py"]